name: rails test
on:
  push:
defaults:
  run:
    working-directory: app
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: app
          bundler-cache: true
      - run: bundle exec rails test
      - run: ./bin/summary_coverage > coverage/summary.csv
      - uses: actions/upload-artifact@v2
        with:
          name: coverage_${{github.head_ref}}
          path: app/coverage
          retention-days: 3
